-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity convert_inputs is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    in_V_V_TDATA : IN STD_LOGIC_VECTOR (327 downto 0);
    in_V_V_TVALID : IN STD_LOGIC;
    in_V_V_TREADY : OUT STD_LOGIC;
    pack_buffer_V_V_din : OUT STD_LOGIC_VECTOR (515 downto 0);
    pack_buffer_V_V_full_n : IN STD_LOGIC;
    pack_buffer_V_V_write : OUT STD_LOGIC );
end;


architecture behav of convert_inputs is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_7A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111010";
    constant ap_const_lv32_A1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100001";
    constant ap_const_lv32_A2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100010";
    constant ap_const_lv32_C9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001001";
    constant ap_const_lv32_CA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001010";
    constant ap_const_lv32_CC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001100";
    constant ap_const_lv32_CD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001101";
    constant ap_const_lv32_CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001110";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_D3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010011";
    constant ap_const_lv32_D4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010100";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100011";
    constant ap_const_lv32_E4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100100";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101000";
    constant ap_const_lv32_EB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101011";
    constant ap_const_lv32_EC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101100";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110011";
    constant ap_const_lv32_F4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110100";
    constant ap_const_lv32_11B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011011";
    constant ap_const_lv32_11C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011100";
    constant ap_const_lv32_143 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000011";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_79 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal in_V_V_TDATA_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_172_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_nbwritereq_fu_180_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal pack_buffer_V_V_blk_n : STD_LOGIC;
    signal ap_predicate_op9_read_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal tmp_32_fu_475_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal output0_first_V_fu_241_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output0_last_V_fu_249_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output0_addr_latch_V_fu_233_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output0_response_V_fu_257_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output1_first_V_fu_273_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output1_last_V_fu_281_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output1_addr_latch_V_fu_265_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_42_i_fu_435_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_43_i_fu_445_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal output2_first_V_fu_347_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output2_last_V_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output2_addr_latch_V_fu_339_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output2_response_V_fu_363_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp7_fu_527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp6_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_40_i_fu_415_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_41_i_fu_425_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal output3_first_V_fu_379_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output3_last_V_fu_387_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp8_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output3_addr_latch_V_fu_371_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_4_i_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_5_i_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_demorgan_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_i_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output3_loop_V_fu_215_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal output3_timestamp_V_fu_205_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal sel_tmp_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_i_not_fu_603_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_sel_tmp_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp9_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_627_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_6_i_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_661_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_5_i_not_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_sel_tmp1_fu_689_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp12_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp11_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp10_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_fu_725_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal output0_a_addr_V_fu_319_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_s_fu_741_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal output0_a_len_V_fu_299_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_751_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Repl2_1_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_s_fu_733_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal output1_a_addr_V_fu_309_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_2_fu_783_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal output1_a_len_V_fu_289_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_793_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal output0_ext_event_V_fu_223_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Repl2_3_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_9_fu_635_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal output2_a_addr_V_fu_465_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal output2_a_id_V_fu_517_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal output2_id_V_fu_513_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal output2_a_len_V_fu_405_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_829_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Repl2_19_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_2_fu_583_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal output3_a_addr_V_fu_455_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal output3_a_id_V_fu_543_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal output3_id_V_fu_539_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal output3_a_len_V_fu_395_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_863_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal output2_ext_event_V_fu_329_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Repl2_5_fu_713_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_4_fu_675_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_16_fu_201_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_Result_i_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_873_p13 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Result_3_fu_839_p11 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Result_2_fu_803_p12 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Result_s_fu_479_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Result_1_fu_761_p10 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Repl2_43_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_36_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_42_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_41_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_39_fu_931_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Repl2_38_fu_939_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Repl2_37_fu_947_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal pack_data0_V_fu_955_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pack_buffer_V_V_full_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, in_V_V_TVALID, pack_buffer_V_V_full_n, ap_predicate_op9_read_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, in_V_V_TVALID, pack_buffer_V_V_full_n, ap_predicate_op9_read_state1)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pack_buffer_V_V_full_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)));
    end process;


    ap_done_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_V_V_TVALID, pack_buffer_V_V_full_n, ap_predicate_op9_read_state1)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pack_buffer_V_V_full_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op9_read_state1_assign_proc : process(tmp_nbreadreq_fu_172_p3, tmp_6_nbwritereq_fu_180_p3)
    begin
                ap_predicate_op9_read_state1 <= ((tmp_6_nbwritereq_fu_180_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_172_p3 = ap_const_lv1_1));
    end process;

    ap_ready <= internal_ap_ready;

    in_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, in_V_V_TVALID, tmp_nbreadreq_fu_172_p3, tmp_6_nbwritereq_fu_180_p3)
    begin
        if (((tmp_6_nbwritereq_fu_180_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_172_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_V_V_TDATA_blk_n <= in_V_V_TVALID;
        else 
            in_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_TREADY_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_V_V_TVALID, pack_buffer_V_V_full_n, ap_predicate_op9_read_state1)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pack_buffer_V_V_full_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
            in_V_V_TREADY <= ap_const_logic_1;
        else 
            in_V_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_V_V_TVALID, pack_buffer_V_V_full_n, ap_predicate_op9_read_state1)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pack_buffer_V_V_full_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    newSel2_fu_725_p3 <= 
        output3_timestamp_V_fu_205_p4 when (p_4_i_fu_495_p2(0) = '1') else 
        ap_const_lv30_0;
    newSel_fu_661_p3 <= 
        ap_const_lv30_0 when (tmp_7_fu_655_p2(0) = '1') else 
        output3_timestamp_V_fu_205_p4;
    not_Result_i_fu_901_p2 <= (tmp_16_fu_201_p1 xor ap_const_lv1_1);
    not_sel_tmp1_fu_689_p2 <= (p_5_i_not_fu_683_p2 or p_4_i_fu_495_p2);
    not_sel_tmp_fu_609_p2 <= (sel_tmp6_demorgan_fu_559_p2 or p_i_not_fu_603_p2);
    or_cond1_fu_649_p2 <= (p_6_i_fu_553_p2 or p_4_i_fu_495_p2);
    or_cond2_fu_669_p2 <= (or_cond_fu_643_p2 or or_cond1_fu_649_p2);
    or_cond_fu_643_p2 <= (sel_tmp7_fu_571_p2 or sel_tmp1_fu_597_p2);
    output0_a_addr_V_fu_319_p4 <= in_V_V_TDATA(201 downto 162);
    output0_a_len_V_fu_299_p4 <= in_V_V_TDATA(57 downto 50);
    output0_addr_latch_V_fu_233_p3 <= in_V_V_TDATA(35 downto 35);
    output0_ext_event_V_fu_223_p4 <= in_V_V_TDATA(34 downto 32);
    output0_first_V_fu_241_p3 <= in_V_V_TDATA(36 downto 36);
    output0_last_V_fu_249_p3 <= in_V_V_TDATA(37 downto 37);
    output0_response_V_fu_257_p3 <= in_V_V_TDATA(38 downto 38);
    output1_a_addr_V_fu_309_p4 <= in_V_V_TDATA(161 downto 122);
    output1_a_len_V_fu_289_p4 <= in_V_V_TDATA(49 downto 42);
    output1_addr_latch_V_fu_265_p3 <= in_V_V_TDATA(39 downto 39);
    output1_first_V_fu_273_p3 <= in_V_V_TDATA(40 downto 40);
    output1_last_V_fu_281_p3 <= in_V_V_TDATA(41 downto 41);
    output2_a_addr_V_fu_465_p4 <= in_V_V_TDATA(323 downto 284);
    output2_a_id_V_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_43_i_fu_445_p4),16));
    output2_a_len_V_fu_405_p4 <= in_V_V_TDATA(227 downto 220);
    output2_addr_latch_V_fu_339_p3 <= in_V_V_TDATA(205 downto 205);
    output2_ext_event_V_fu_329_p4 <= in_V_V_TDATA(204 downto 202);
    output2_first_V_fu_347_p3 <= in_V_V_TDATA(206 downto 206);
    output2_id_V_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_42_i_fu_435_p4),16));
    output2_last_V_fu_355_p3 <= in_V_V_TDATA(207 downto 207);
    output2_response_V_fu_363_p3 <= in_V_V_TDATA(208 downto 208);
    output3_a_addr_V_fu_455_p4 <= in_V_V_TDATA(283 downto 244);
    output3_a_id_V_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_41_i_fu_425_p4),16));
    output3_a_len_V_fu_395_p4 <= in_V_V_TDATA(219 downto 212);
    output3_addr_latch_V_fu_371_p3 <= in_V_V_TDATA(209 downto 209);
    output3_first_V_fu_379_p3 <= in_V_V_TDATA(210 downto 210);
    output3_id_V_fu_539_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_40_i_fu_415_p4),16));
    output3_last_V_fu_387_p3 <= in_V_V_TDATA(211 downto 211);
    output3_loop_V_fu_215_p3 <= in_V_V_TDATA(31 downto 31);
    output3_timestamp_V_fu_205_p4 <= in_V_V_TDATA(30 downto 1);
    p_4_i_fu_495_p2 <= (tmp3_fu_489_p2 or tmp2_fu_483_p2);
    p_5_i_fu_507_p2 <= (tmp4_fu_501_p2 or output1_addr_latch_V_fu_265_p3);
    p_5_i_not_fu_683_p2 <= (p_5_i_fu_507_p2 xor ap_const_lv1_1);
    p_6_i_fu_553_p2 <= (tmp8_fu_547_p2 or output3_addr_latch_V_fu_371_p3);
    p_Repl2_19_fu_577_p2 <= (sel_tmp7_fu_571_p2 and output3_loop_V_fu_215_p3);
    p_Repl2_1_fu_719_p2 <= (p_4_i_fu_495_p2 and output3_loop_V_fu_215_p3);
    p_Repl2_2_fu_583_p3 <= 
        output3_timestamp_V_fu_205_p4 when (sel_tmp7_fu_571_p2(0) = '1') else 
        ap_const_lv30_0;
    p_Repl2_36_fu_913_p2 <= (p_i_fu_533_p2 and not_Result_i_fu_901_p2);
    p_Repl2_37_fu_947_p3 <= 
        ap_const_lv128_lc_1 when (tmp_16_fu_201_p1(0) = '1') else 
        p_Result_2_fu_803_p12;
    p_Repl2_38_fu_939_p3 <= 
        ap_const_lv128_lc_1 when (tmp_16_fu_201_p1(0) = '1') else 
        p_Result_3_fu_839_p11;
    p_Repl2_39_fu_931_p3 <= 
        ap_const_lv128_lc_1 when (tmp_16_fu_201_p1(0) = '1') else 
        p_Result_4_fu_873_p13;
    p_Repl2_3_fu_621_p2 <= (tmp9_fu_615_p2 and sel_tmp1_fu_597_p2);
    p_Repl2_41_fu_925_p2 <= (tmp_16_fu_201_p1 or p_4_i_fu_495_p2);
    p_Repl2_42_fu_919_p2 <= (p_5_i_fu_507_p2 and not_Result_i_fu_901_p2);
    p_Repl2_43_fu_907_p2 <= (p_6_i_fu_553_p2 and not_Result_i_fu_901_p2);
    p_Repl2_4_fu_675_p3 <= 
        newSel_fu_661_p3 when (or_cond2_fu_669_p2(0) = '1') else 
        ap_const_lv30_0;
    p_Repl2_5_fu_713_p2 <= (tmp11_fu_707_p2 and tmp10_fu_695_p2);
    p_Repl2_9_fu_635_p3 <= 
        ap_const_lv30_0 when (sel_tmp7_fu_571_p2(0) = '1') else 
        sel_tmp2_fu_627_p3;
    p_Repl2_s_fu_733_p3 <= 
        ap_const_lv30_0 when (or_cond_fu_643_p2(0) = '1') else 
        newSel2_fu_725_p3;
    p_Result_1_fu_761_p10 <= ((((((((ap_const_lv7_0 & output0_a_addr_V_fu_319_p4) & tmp_s_fu_741_p4) & output0_a_len_V_fu_299_p4) & tmp_1_fu_751_p4) & ap_const_lv2_2) & p_Repl2_1_fu_719_p2) & p_Repl2_s_fu_733_p3) & ap_const_lv1_0);
    p_Result_2_fu_803_p12 <= ((((((((((ap_const_lv7_0 & output1_a_addr_V_fu_309_p4) & tmp_2_fu_783_p4) & output1_a_len_V_fu_289_p4) & ap_const_lv1_0) & tmp_3_fu_793_p4) & output0_ext_event_V_fu_223_p4) & ap_const_lv2_0) & p_Repl2_3_fu_621_p2) & p_Repl2_9_fu_635_p3) & ap_const_lv1_0);
    p_Result_3_fu_839_p11 <= (((((((((ap_const_lv7_0 & output2_a_addr_V_fu_465_p4) & output2_a_id_V_fu_517_p1) & output2_id_V_fu_513_p1) & output2_a_len_V_fu_405_p4) & tmp_4_fu_829_p4) & ap_const_lv2_3) & p_Repl2_19_fu_577_p2) & p_Repl2_2_fu_583_p3) & ap_const_lv1_0);
    p_Result_40_i_fu_415_p4 <= in_V_V_TDATA(231 downto 228);
    p_Result_41_i_fu_425_p4 <= in_V_V_TDATA(235 downto 232);
    p_Result_42_i_fu_435_p4 <= in_V_V_TDATA(239 downto 236);
    p_Result_43_i_fu_445_p4 <= in_V_V_TDATA(243 downto 240);
    p_Result_4_fu_873_p13 <= (((((((((((ap_const_lv7_0 & output3_a_addr_V_fu_455_p4) & output3_a_id_V_fu_543_p1) & output3_id_V_fu_539_p1) & output3_a_len_V_fu_395_p4) & ap_const_lv1_0) & tmp_5_fu_863_p4) & output2_ext_event_V_fu_329_p4) & ap_const_lv2_1) & p_Repl2_5_fu_713_p2) & p_Repl2_4_fu_675_p3) & ap_const_lv1_0);
    p_Result_s_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_475_p1),128));
    p_i_fu_533_p2 <= (tmp7_fu_527_p2 or tmp6_fu_521_p2);
    p_i_not_fu_603_p2 <= (p_i_fu_533_p2 xor ap_const_lv1_1);

    pack_buffer_V_V_blk_n_assign_proc : process(ap_CS_fsm_state1, pack_buffer_V_V_full_n, tmp_nbreadreq_fu_172_p3, tmp_6_nbwritereq_fu_180_p3)
    begin
        if (((tmp_6_nbwritereq_fu_180_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_172_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pack_buffer_V_V_blk_n <= pack_buffer_V_V_full_n;
        else 
            pack_buffer_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pack_buffer_V_V_din <= (((((((p_Repl2_43_fu_907_p2 & p_Repl2_36_fu_913_p2) & p_Repl2_42_fu_919_p2) & p_Repl2_41_fu_925_p2) & p_Repl2_39_fu_931_p3) & p_Repl2_38_fu_939_p3) & p_Repl2_37_fu_947_p3) & pack_data0_V_fu_955_p3);

    pack_buffer_V_V_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_V_V_TVALID, pack_buffer_V_V_full_n, ap_predicate_op9_read_state1)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pack_buffer_V_V_full_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
            pack_buffer_V_V_write <= ap_const_logic_1;
        else 
            pack_buffer_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    pack_data0_V_fu_955_p3 <= 
        p_Result_s_fu_479_p1 when (tmp_16_fu_201_p1(0) = '1') else 
        p_Result_1_fu_761_p10;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    sel_tmp1_fu_597_p2 <= (sel_tmp_fu_591_p2 and p_5_i_fu_507_p2);
    sel_tmp2_fu_627_p3 <= 
        output3_timestamp_V_fu_205_p4 when (sel_tmp1_fu_597_p2(0) = '1') else 
        ap_const_lv30_0;
    sel_tmp6_demorgan_fu_559_p2 <= (p_5_i_fu_507_p2 or p_4_i_fu_495_p2);
    sel_tmp6_fu_565_p2 <= (sel_tmp6_demorgan_fu_559_p2 xor ap_const_lv1_1);
    sel_tmp7_fu_571_p2 <= (sel_tmp6_fu_565_p2 and p_i_fu_533_p2);
    sel_tmp_fu_591_p2 <= (p_4_i_fu_495_p2 xor ap_const_lv1_1);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp10_fu_695_p2 <= (p_6_i_fu_553_p2 and output3_loop_V_fu_215_p3);
    tmp11_fu_707_p2 <= (tmp12_fu_701_p2 and sel_tmp_fu_591_p2);
    tmp12_fu_701_p2 <= (not_sel_tmp_fu_609_p2 and not_sel_tmp1_fu_689_p2);
    tmp2_fu_483_p2 <= (output0_last_V_fu_249_p3 or output0_first_V_fu_241_p3);
    tmp3_fu_489_p2 <= (output0_response_V_fu_257_p3 or output0_addr_latch_V_fu_233_p3);
    tmp4_fu_501_p2 <= (output1_last_V_fu_281_p3 or output1_first_V_fu_273_p3);
    tmp6_fu_521_p2 <= (output2_last_V_fu_355_p3 or output2_first_V_fu_347_p3);
    tmp7_fu_527_p2 <= (output2_response_V_fu_363_p3 or output2_addr_latch_V_fu_339_p3);
    tmp8_fu_547_p2 <= (output3_last_V_fu_387_p3 or output3_first_V_fu_379_p3);
    tmp9_fu_615_p2 <= (output3_loop_V_fu_215_p3 and not_sel_tmp_fu_609_p2);
    tmp_16_fu_201_p1 <= in_V_V_TDATA(1 - 1 downto 0);
    tmp_1_fu_751_p4 <= in_V_V_TDATA(38 downto 32);
    tmp_2_fu_783_p4 <= in_V_V_TDATA(89 downto 58);
    tmp_32_fu_475_p1 <= in_V_V_TDATA(64 - 1 downto 0);
    tmp_3_fu_793_p4 <= in_V_V_TDATA(41 downto 39);
    tmp_4_fu_829_p4 <= in_V_V_TDATA(208 downto 202);
    tmp_5_fu_863_p4 <= in_V_V_TDATA(211 downto 209);
    tmp_6_nbwritereq_fu_180_p3 <= (0=>pack_buffer_V_V_full_n, others=>'-');
    tmp_7_fu_655_p2 <= (p_4_i_fu_495_p2 or or_cond_fu_643_p2);
    tmp_nbreadreq_fu_172_p3 <= (0=>in_V_V_TVALID, others=>'-');
    tmp_s_fu_741_p4 <= in_V_V_TDATA(121 downto 90);
end behav;
