#------------------------------------------------------------------
# This code is intended to be used to check the output files (gdt_data_xxx.txt) generated by
# gaussian_delay.py. It will load the generated output file, and plot a histogram.
#------------------------------------------------------------------

import csv
from collections import Counter  # for debug only
import matplotlib.pyplot as plt

delay    = []   # create empty array to store the delays read from file
i        = 0    # only needed for debugging the code
path     = "../../../../../shared/"
filename = "gdt_data_g72_mu_div128.txt"

with open(path + filename, 'r') as fd:
#with open('../../../../../shared/gdt_data_g216.txt', 'r') as fd:
    reader = csv.reader(fd)
    for row in reader:
        delay.append(int(row[0],0))   
        # print(delay[i])  # for debug only
        # i = i + 1        # for debug only

plt.hist(delay, bins = 128)
plt.title(filename)
plt.xlabel("Delay (clock cycles)", fontsize=12)  
plt.ylabel("Occurances in GDT (1024 Total Entries)", fontsize=12)
plt.show()

#------------------------------------------------------------------
# For debug only. The following line create a library of delay read from the input file.
# The library will list the occurances of each delay found in the file
#------------------------------------------------------------------
#histo_x = Counter(delay)  # create library of delays, listing the occurances for each
#print(histo_x)

