set_property -dict [list CONFIG.PSU__FPGA_PL1_ENABLE {1} CONFIG.PSU__CRL_APB__PL1_REF_CTRL__SRCSEL {IOPLL} CONFIG.PSU__CRL_APB__PL1_REF_CTRL__FREQMHZ {300}] [get_bd_cells zynq_ultra_ps_e_0]
copy_bd_objs /  [get_bd_cells {rst_ps8_0_299M}]
apply_bd_automation -rule xilinx.com:bd_rule:clkrst -config {Clk "/zynq_ultra_ps_e_0/pl_clk1 (299 MHz)" }  [get_bd_pins rst_ps8_0_299M1/slowest_sync_clk]
set_property -dict [list CONFIG.PSU__NUM_FABRIC_RESETS {2}] [get_bd_cells zynq_ultra_ps_e_0]
connect_bd_net [get_bd_pins zynq_ultra_ps_e_0/pl_resetn1] [get_bd_pins rst_ps8_0_299M1/ext_reset_in]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins zynq_ultra_ps_e_0/saxihp0_fpd_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins zynq_ultra_ps_e_0/saxihp1_fpd_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins zynq_ultra_ps_e_0/saxihp2_fpd_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins zynq_ultra_ps_e_0/saxihp3_fpd_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins zynq_ultra_ps_e_0/maxihpm0_fpd_aclk]
connect_bd_net [get_bd_pins zynq_ultra_ps_e_0/maxihpm0_fpd_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins zynq_ultra_ps_e_0/saxihp0_fpd_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins zynq_ultra_ps_e_0/saxihp1_fpd_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins zynq_ultra_ps_e_0/saxihp2_fpd_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins zynq_ultra_ps_e_0/saxihp3_fpd_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_0/s_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_0/m_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_1/s_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_1/m_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_2/m_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_3/m_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_2/s_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_shim_3/s_axi_aclk]
connect_bd_net [get_bd_pins axi_shim_0/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_shim_0/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_shim_1/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_shim_1/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_shim_2/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_shim_2/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_shim_3/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_shim_3/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins smartconnect_0/aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins smartconnect_1/aclk]
connect_bd_net [get_bd_pins smartconnect_0/aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins smartconnect_1/aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_0/s_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_1/s_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_2/s_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_3/s_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_0/m_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_1/m_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_2/m_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_delay_3/m_axi_aclk]
connect_bd_net [get_bd_pins axi_delay_0/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_delay_1/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_delay_2/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_delay_3/s_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_delay_0/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_delay_1/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_delay_2/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_delay_3/m_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_perf_mon_0/core_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_perf_mon_0/m_axis_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_perf_mon_0/slot_0_axi_aclk]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_perf_mon_0/slot_1_axi_aclk]
connect_bd_net [get_bd_pins axi_perf_mon_0/core_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_perf_mon_0/m_axis_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_perf_mon_0/slot_0_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_perf_mon_0/slot_1_axi_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
disconnect_bd_net /zynq_ultra_ps_e_0_pl_clk0 [get_bd_pins axi_tcd_0/s_axis_aclk]
connect_bd_net [get_bd_pins axi_tcd_0/s_axis_aclk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
disconnect_bd_net /engine_0/microblaze_0_Clk [get_bd_pins engine_0/axi_interconnect_0/ACLK]
disconnect_bd_net /engine_0/microblaze_0_Clk [get_bd_pins engine_0/axi_interconnect_0/M00_ACLK]
connect_bd_net [get_bd_pins engine_0/axi_interconnect_0/ACLK] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins engine_0/ACLK] [get_bd_pins engine_0/axi_interconnect_0/M00_ACLK]
disconnect_bd_net /engine_0/rst_microblaze_0_Clk_100M_interconnect_aresetn [get_bd_pins engine_0/axi_interconnect_0/M00_ARESETN]
connect_bd_net [get_bd_pins engine_0/axi_interconnect_0/M00_ARESETN] [get_bd_pins rst_ps8_0_299M1/peripheral_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_0/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_1/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_2/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_3/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_0/m_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_1/m_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_2/m_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_shim_3/m_axi_aresetn]
connect_bd_net [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn] [get_bd_pins axi_shim_0/s_axi_aresetn]
connect_bd_net [get_bd_pins axi_shim_0/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_shim_1/s_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_shim_1/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_shim_2/s_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_shim_2/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_shim_3/s_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_shim_3/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_0/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_1/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_2/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_3/s_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_0/m_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_1/m_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_2/m_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_delay_3/m_axi_aresetn]
connect_bd_net [get_bd_pins axi_delay_0/s_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_delay_0/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_delay_1/s_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_delay_1/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_delay_2/s_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_delay_2/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_delay_3/s_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_delay_3/m_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins smartconnect_1/aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins smartconnect_0/aresetn]
connect_bd_net [get_bd_pins smartconnect_0/aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_tcd_0/s_axis_aresetn]
connect_bd_net [get_bd_pins axi_tcd_0/s_axis_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_perf_mon_0/m_axis_aresetn]
connect_bd_net [get_bd_pins axi_perf_mon_0/m_axis_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_perf_mon_0/core_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_perf_mon_0/slot_0_axi_aresetn]
disconnect_bd_net /rst_ps8_0_299M_peripheral_aresetn [get_bd_pins axi_perf_mon_0/slot_1_axi_aresetn]
connect_bd_net [get_bd_pins axi_perf_mon_0/core_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_perf_mon_0/slot_0_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_perf_mon_0/slot_1_axi_aresetn] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
disconnect_bd_net /engine_0/rst_microblaze_0_Clk_100M_interconnect_aresetn [get_bd_pins engine_0/axi_interconnect_0/ARESETN]
connect_bd_net [get_bd_pins engine_0/axi_interconnect_0/ARESETN] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]


save_bd_design
validate_bd_design


create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_1
delete_bd_objs [get_bd_intf_nets axi_shim_3_m_axi]
connect_bd_intf_net [get_bd_intf_pins axi_shim_3/m_axi] -boundary_type upper [get_bd_intf_pins axi_interconnect_1/S00_AXI]
delete_bd_objs [get_bd_intf_nets smartconnect_1_M00_AXI]
connect_bd_intf_net [get_bd_intf_pins axi_delay_2/s_axi] -boundary_type upper [get_bd_intf_pins axi_interconnect_1/M00_AXI]
delete_bd_objs [get_bd_intf_nets smartconnect_1_M01_AXI]
connect_bd_intf_net [get_bd_intf_pins axi_delay_3/s_axi] -boundary_type upper [get_bd_intf_pins axi_interconnect_1/M01_AXI]
connect_bd_net [get_bd_pins axi_interconnect_1/ACLK] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_interconnect_1/ARESETN] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_interconnect_1/S00_ACLK] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_interconnect_1/M00_ACLK] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_interconnect_1/M01_ACLK] [get_bd_pins zynq_ultra_ps_e_0/pl_clk1]
connect_bd_net [get_bd_pins axi_interconnect_1/S00_ARESETN] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_interconnect_1/M00_ARESETN] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
connect_bd_net [get_bd_pins axi_interconnect_1/M01_ARESETN] [get_bd_pins rst_ps8_0_299M1/interconnect_aresetn]
delete_bd_objs [get_bd_cells smartconnect_1]
set_property -dict [list CONFIG.C_AXI_ID_WIDTH {4}] [get_bd_cells axi_shim_2]
set_property -dict [list CONFIG.C_AXI_ID_WIDTH {4}] [get_bd_cells axi_shim_3]

set_property -dict [list CONFIG.XBAR_DATA_WIDTH.VALUE_SRC USER] [get_bd_cells axi_interconnect_1]
set_property -dict [list CONFIG.ENABLE_ADVANCED_OPTIONS {1} CONFIG.XBAR_DATA_WIDTH {64}] [get_bd_cells axi_interconnect_1]

set_property -dict [list CONFIG.XBAR_DATA_WIDTH.VALUE_SRC USER] [get_bd_cells engine_0/axi_interconnect_0]
set_property -dict [list CONFIG.ENABLE_ADVANCED_OPTIONS {1} CONFIG.XBAR_DATA_WIDTH {64}] [get_bd_cells engine_0/axi_interconnect_0]
