// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="eth_fifo_interface,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-i,HLS_INPUT_CLOCK=3.333333,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.607000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=453,HLS_SYN_LUT=1585,HLS_VERSION=2018_2}" *)

module eth_fifo_interface (
        ap_clk,
        ap_rst_n,
        dma_tx_end_tog_V,
        tx_r_fixed_lat_V,
        tx_r_rd_V,
        tx_r_status_V,
        data_in_V_V_TDATA,
        data_in_V_V_TVALID,
        data_in_V_V_TREADY,
        dma_tx_status_tog_V,
        tx_r_control_V,
        tx_r_data_V,
        tx_r_data_rdy_V,
        tx_r_eop_V,
        tx_r_err_V,
        tx_r_flushed_V,
        tx_r_sop_V,
        tx_r_underflow_V,
        tx_r_valid_V
);

parameter    ap_ST_fsm_state1 = 1'd1;
parameter    ap_const_lv14_0 = 14'd0;

input   ap_clk;
input   ap_rst_n;
input  [0:0] dma_tx_end_tog_V;
input  [0:0] tx_r_fixed_lat_V;
input  [0:0] tx_r_rd_V;
input  [3:0] tx_r_status_V;
input  [127:0] data_in_V_V_TDATA;
input   data_in_V_V_TVALID;
output   data_in_V_V_TREADY;
output  [0:0] dma_tx_status_tog_V;
output  [0:0] tx_r_control_V;
output  [7:0] tx_r_data_V;
output  [0:0] tx_r_data_rdy_V;
output  [0:0] tx_r_eop_V;
output  [0:0] tx_r_err_V;
output  [0:0] tx_r_flushed_V;
output  [0:0] tx_r_sop_V;
output  [0:0] tx_r_underflow_V;
output  [0:0] tx_r_valid_V;

reg data_in_V_V_TREADY;

 reg    ap_rst_n_inv;
reg   [0:0] last_tx_status_valid;
reg   [13:0] buffer_count_V;
reg   [0:0] data_ready_V;
reg   [0:0] tx_valid_V;
reg   [0:0] sop_V;
reg   [0:0] eop_V;
reg   [7:0] tx_data_V;
reg   [2:0] current_state;
reg   [15:0] length_V;
reg   [13:0] count_V;
reg   [0:0] buffer_added;
reg   [7:0] buffer_data_V;
reg   [7:0] ID_num_V;
reg   [0:0] data_word_valid;
reg   [3:0] word_byte_V;
reg   [127:0] data_word_V;
reg    data_in_V_V_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] brmerge8_fu_1357_p2;
wire   [13:0] grp_fu_709_p2;
reg   [13:0] ap_phi_mux_storemerge1_phi_fu_420_p4;
wire   [7:0] data_buffer_V_V_dout;
wire    data_buffer_V_V_empty_n;
reg    data_buffer_V_V_read;
wire   [2:0] current_state_load_load_fu_798_p1;
wire   [0:0] tx_r_rd_V_read_read_fu_288_p2;
wire   [0:0] tmp_2_fu_819_p2;
wire   [0:0] tmp_nbreadreq_fu_307_p3;
reg    ap_predicate_op95_read_state1;
reg    ap_predicate_op110_read_state1;
wire    data_buffer_V_V_full_n;
reg    data_buffer_V_V_write;
wire   [0:0] brmerge1016_demorgan_fu_1127_p2;
reg    ap_block_state1;
reg   [13:0] ap_phi_mux_storemerge2_phi_fu_430_p4;
reg   [0:0] ap_phi_mux_sop_V_new_1_phi_fu_440_p26;
wire   [0:0] tmp_6_fu_1029_p2;
reg   [0:0] ap_phi_mux_eop_V_new_phi_fu_483_p26;
reg   [0:0] ap_phi_mux_buffer_removed_5_phi_fu_527_p26;
reg   [7:0] temp_data_V_15_fu_1153_p4;
reg   [7:0] ap_phi_mux_tmp_V_3_phi_fu_571_p34;
wire   [3:0] word_byte_V_load_load_fu_1145_p1;
reg   [7:0] temp_data_V_14_fu_1164_p4;
reg   [7:0] temp_data_V_13_fu_1175_p4;
reg   [7:0] temp_data_V_12_fu_1186_p4;
reg   [7:0] temp_data_V_11_fu_1197_p4;
reg   [7:0] temp_data_V_10_fu_1208_p4;
reg   [7:0] temp_data_V_9_fu_1219_p4;
reg   [7:0] temp_data_V_8_fu_1230_p4;
reg   [7:0] temp_data_V_7_fu_1241_p4;
reg   [7:0] temp_data_V_6_fu_1252_p4;
reg   [7:0] temp_data_V_5_fu_1263_p4;
reg   [7:0] temp_data_V_4_fu_1274_p4;
reg   [7:0] temp_data_V_3_fu_1285_p4;
reg   [7:0] temp_data_V_2_fu_1296_p4;
reg   [7:0] temp_data_V_1_fu_1307_p4;
reg   [7:0] temp_data_V_fu_1318_p4;
reg   [0:0] ap_phi_mux_buffer_added_new_phi_fu_612_p4;
reg   [0:0] ap_phi_mux_data_word_valid_flag_phi_fu_623_p4;
wire   [0:0] tmp_17_fu_1329_p2;
reg   [0:0] ap_phi_mux_word_byte_V_flag_phi_fu_633_p4;
wire   [0:0] not_tmp_s_fu_1343_p2;
wire   [3:0] tmp_18_fu_1336_p2;
reg   [0:0] ap_phi_mux_data_word_valid_load_1_phi_fu_653_p4;
reg   [0:0] ap_phi_mux_data_word_valid_flag_1_phi_fu_662_p4;
reg   [0:0] ap_phi_mux_data_word_valid_new_1_phi_fu_673_p4;
reg   [0:0] ap_phi_mux_word_byte_V_flag_1_phi_fu_684_p4;
reg   [3:0] ap_phi_mux_word_byte_V_new_1_phi_fu_695_p4;
wire   [13:0] tmp_20_fu_1399_p2;
wire   [0:0] brmerge1_fu_1381_p2;
wire   [13:0] tmp_21_fu_1423_p2;
wire   [0:0] brmerge2_fu_1417_p2;
wire   [7:0] storemerge_in_in_fu_891_p3;
wire   [7:0] tmp_4_fu_943_p8;
wire   [7:0] tmp_3_fu_995_p8;
wire   [0:0] packet_buffered_fu_761_p2;
wire   [0:0] demorgan_fu_1054_p2;
wire   [15:0] p_cast_fu_1106_p1;
wire   [13:0] tmp_14_fu_909_p2;
wire   [0:0] buffer_added_load_load_fu_811_p1;
wire   [0:0] p_not_fu_1048_p2;
wire   [7:0] tmp_8_fu_841_p2;
wire   [0:0] tmp_s_fu_871_p2;
wire   [7:0] p_Result_7_fu_877_p4;
wire   [7:0] tmp_23_fu_887_p1;
wire   [13:0] tmp_24_fu_905_p1;
wire   [2:0] tmp_22_fu_933_p1;
wire   [2:0] tmp_4_fu_943_p7;
wire   [2:0] tmp_11_fu_985_p1;
wire   [2:0] tmp_3_fu_995_p7;
reg   [3:0] p_Result_6_fu_1019_p4;
wire   [0:0] demorgan_fu_1054_p0;
reg   [9:0] p_Result_s_fu_1060_p4;
reg   [13:0] p_Result_2_fu_1070_p5;
wire   [14:0] tmp_15_cast_fu_1088_p1;
wire   [0:0] tmp_9_fu_1082_p2;
wire   [14:0] tmp_5_fu_1092_p2;
wire   [14:0] p_s_fu_1098_p3;
wire   [0:0] brmerge1016_demorgan_fu_1127_p1;
wire   [0:0] tmp_27_not_fu_1351_p0;
wire   [0:0] tmp_27_not_fu_1351_p2;
wire   [0:0] p_not1_fu_1375_p2;
wire   [0:0] buffer_removed_5_not_fu_1411_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_condition_733;
reg    ap_condition_736;
reg    ap_condition_109;
reg    ap_condition_193;

// power-on initialization
initial begin
#0 last_tx_status_valid = 1'd0;
#0 buffer_count_V = 14'd0;
#0 data_ready_V = 1'd0;
#0 tx_valid_V = 1'd0;
#0 sop_V = 1'd0;
#0 eop_V = 1'd0;
#0 tx_data_V = 8'd0;
#0 current_state = 3'd0;
#0 length_V = 16'd0;
#0 count_V = 14'd16000;
#0 buffer_added = 1'd0;
#0 buffer_data_V = 8'd0;
#0 ID_num_V = 8'd0;
#0 data_word_valid = 1'd0;
#0 word_byte_V = 4'd0;
#0 data_word_V = 128'd0;
#0 ap_CS_fsm = 1'd1;
end

eth_fifo_interfacbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
eth_fifo_interfacbkb_U1(
    .din0(8'd0),
    .din1(8'd10),
    .din2(8'd53),
    .din3(8'd3),
    .din4(8'd89),
    .din5(8'd245),
    .din6(tmp_4_fu_943_p7),
    .dout(tmp_4_fu_943_p8)
);

eth_fifo_interfacbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
eth_fifo_interfacbkb_U2(
    .din0(8'd255),
    .din1(8'd255),
    .din2(8'd255),
    .din3(8'd255),
    .din4(8'd255),
    .din5(8'd255),
    .din6(tmp_3_fu_995_p7),
    .dout(tmp_3_fu_995_p8)
);

fifo_w8_d16384_A data_buffer_V_V_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ap_phi_mux_tmp_V_3_phi_fu_571_p34),
    .if_full_n(data_buffer_V_V_full_n),
    .if_write(data_buffer_V_V_write),
    .if_dout(data_buffer_V_V_dout),
    .if_empty_n(data_buffer_V_V_empty_n),
    .if_read(data_buffer_V_V_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_109)) begin
        if (((brmerge1_fu_1381_p2 == 1'd1) & (brmerge2_fu_1417_p2 == 1'd0))) begin
            buffer_count_V <= tmp_21_fu_1423_p2;
        end else if ((brmerge1_fu_1381_p2 == 1'd0)) begin
            buffer_count_V <= tmp_20_fu_1399_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (packet_buffered_fu_761_p2 == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (demorgan_fu_1054_p2 == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd0) & (packet_buffered_fu_761_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_V <= 14'd6;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        count_V <= ap_phi_mux_storemerge2_phi_fu_430_p4;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        count_V <= ap_phi_mux_storemerge1_phi_fu_420_p4;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_predicate_op110_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        count_V <= tmp_14_fu_909_p2;
    end else if (((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state == 3'd3) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd5) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (current_state_load_load_fu_798_p1 == 3'd0) & (p_not_fu_1048_p2 == 1'd0) & (buffer_added_load_load_fu_811_p1 == 1'd0) & (demorgan_fu_1054_p2 == 1'd0) & (packet_buffered_fu_761_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_V <= grp_fu_709_p2;
    end else if (((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (buffer_added_load_load_fu_811_p1 == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd0) & (demorgan_fu_1054_p2 == 1'd0) & (packet_buffered_fu_761_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_V <= 14'd16000;
    end
end

always @ (posedge ap_clk) begin
    if (((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (packet_buffered_fu_761_p2 == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (demorgan_fu_1054_p2 == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd0) & (packet_buffered_fu_761_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_state <= 3'd1;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_state <= 3'd2;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        current_state <= 3'd3;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_predicate_op110_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_state <= 3'd4;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_nbreadreq_fu_307_p3 == 1'd0) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        current_state <= 3'd5;
    end else if (((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd5) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_state <= 3'd6;
    end else if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1))) begin
        current_state <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_109)) begin
        if ((current_state_load_load_fu_798_p1 == 3'd1)) begin
            data_ready_V <= 1'd1;
        end else if ((current_state_load_load_fu_798_p1 == 3'd2)) begin
            data_ready_V <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_193)) begin
        if ((packet_buffered_fu_761_p2 == 1'd1)) begin
                        length_V[0] <= 1'b1;
            length_V[1] <= 1'b0;
            length_V[2] <= 1'b0;
            length_V[3] <= 1'b0;
            length_V[4] <= 1'b1;
            length_V[5] <= 1'b0;
            length_V[6] <= 1'b1;
            length_V[7] <= 1'b1;
            length_V[8] <= 1'b1;
            length_V[9] <= 1'b0;
            length_V[10] <= 1'b1;
            length_V[11] <= 1'b0;
            length_V[12] <= 1'b0;
            length_V[13] <= 1'b0;
            length_V[14] <= 1'b0;
        end else if (((demorgan_fu_1054_p2 == 1'd1) & (packet_buffered_fu_761_p2 == 1'd0))) begin
                        length_V[14 : 0] <= p_cast_fu_1106_p1[14 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_109)) begin
        if ((current_state_load_load_fu_798_p1 == 3'd1)) begin
            tx_data_V <= tmp_3_fu_995_p8;
        end else if ((current_state_load_load_fu_798_p1 == 3'd2)) begin
            tx_data_V <= tmp_4_fu_943_p8;
        end else if ((current_state == 3'd3)) begin
            tx_data_V <= storemerge_in_in_fu_891_p3;
        end else if ((current_state == 3'd4)) begin
            tx_data_V <= buffer_data_V;
        end else if ((current_state_load_load_fu_798_p1 == 3'd5)) begin
            tx_data_V <= 8'd0;
        end else if ((current_state_load_load_fu_798_p1 == 3'd6)) begin
            tx_data_V <= ID_num_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1))) begin
        ID_num_V <= tmp_8_fu_841_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_added <= ap_phi_mux_buffer_added_new_phi_fu_612_p4;
        eop_V <= ap_phi_mux_eop_V_new_phi_fu_483_p26;
        last_tx_status_valid <= dma_tx_end_tog_V;
        sop_V <= ap_phi_mux_sop_V_new_1_phi_fu_440_p26;
        tx_valid_V <= tx_r_rd_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_predicate_op110_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_predicate_op95_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        buffer_data_V <= data_buffer_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (brmerge8_fu_1357_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_word_V <= data_in_V_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_phi_mux_data_word_valid_flag_1_phi_fu_662_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_word_valid <= ap_phi_mux_data_word_valid_new_1_phi_fu_673_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_phi_mux_word_byte_V_flag_1_phi_fu_684_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        word_byte_V <= ap_phi_mux_word_byte_V_new_1_phi_fu_695_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge1016_demorgan_fu_1127_p2 == 1'd1)) begin
            ap_phi_mux_buffer_added_new_phi_fu_612_p4 = 1'd1;
        end else if ((brmerge1016_demorgan_fu_1127_p2 == 1'd0)) begin
            ap_phi_mux_buffer_added_new_phi_fu_612_p4 = 1'd0;
        end else begin
            ap_phi_mux_buffer_added_new_phi_fu_612_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_buffer_added_new_phi_fu_612_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd3) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_nbreadreq_fu_307_p3 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_buffer_removed_5_phi_fu_527_p26 = 1'd1;
    end else if ((((current_state == 3'd3) & (tx_r_rd_V_read_read_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tx_r_rd_V == 1'd1) & (current_state == 3'd3) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (1'b1 == ap_CS_fsm_state1)) | ((tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_nbreadreq_fu_307_p3 == 1'd0) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state == 3'd4) & (tx_r_rd_V_read_read_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd5) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd7) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_buffer_removed_5_phi_fu_527_p26 = 1'd0;
    end else begin
        ap_phi_mux_buffer_removed_5_phi_fu_527_p26 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge8_fu_1357_p2 == 1'd0)) begin
            ap_phi_mux_data_word_valid_flag_1_phi_fu_662_p4 = 1'd1;
        end else if ((brmerge8_fu_1357_p2 == 1'd1)) begin
            ap_phi_mux_data_word_valid_flag_1_phi_fu_662_p4 = ap_phi_mux_data_word_valid_flag_phi_fu_623_p4;
        end else begin
            ap_phi_mux_data_word_valid_flag_1_phi_fu_662_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_word_valid_flag_1_phi_fu_662_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge1016_demorgan_fu_1127_p2 == 1'd1)) begin
            ap_phi_mux_data_word_valid_flag_phi_fu_623_p4 = tmp_17_fu_1329_p2;
        end else if ((brmerge1016_demorgan_fu_1127_p2 == 1'd0)) begin
            ap_phi_mux_data_word_valid_flag_phi_fu_623_p4 = 1'd0;
        end else begin
            ap_phi_mux_data_word_valid_flag_phi_fu_623_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_word_valid_flag_phi_fu_623_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge1016_demorgan_fu_1127_p2 == 1'd1)) begin
            ap_phi_mux_data_word_valid_load_1_phi_fu_653_p4 = not_tmp_s_fu_1343_p2;
        end else if ((brmerge1016_demorgan_fu_1127_p2 == 1'd0)) begin
            ap_phi_mux_data_word_valid_load_1_phi_fu_653_p4 = data_word_valid;
        end else begin
            ap_phi_mux_data_word_valid_load_1_phi_fu_653_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_word_valid_load_1_phi_fu_653_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge8_fu_1357_p2 == 1'd0)) begin
            ap_phi_mux_data_word_valid_new_1_phi_fu_673_p4 = 1'd1;
        end else if ((brmerge8_fu_1357_p2 == 1'd1)) begin
            ap_phi_mux_data_word_valid_new_1_phi_fu_673_p4 = 1'd0;
        end else begin
            ap_phi_mux_data_word_valid_new_1_phi_fu_673_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_word_valid_new_1_phi_fu_673_p4 = 'bx;
    end
end

always @ (*) begin
    if (((current_state_load_load_fu_798_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_eop_V_new_phi_fu_483_p26 = 1'd1;
    end else if ((((current_state == 3'd3) & (tx_r_rd_V_read_read_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd3) & (1'b1 == ap_CS_fsm_state1)) | ((tx_r_rd_V == 1'd1) & (current_state == 3'd3) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_nbreadreq_fu_307_p3 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_nbreadreq_fu_307_p3 == 1'd0) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state == 3'd4) & (tx_r_rd_V_read_read_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd5) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd7) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_eop_V_new_phi_fu_483_p26 = 1'd0;
    end else begin
        ap_phi_mux_eop_V_new_phi_fu_483_p26 = 'bx;
    end
end

always @ (*) begin
    if (((current_state_load_load_fu_798_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_sop_V_new_1_phi_fu_440_p26 = tmp_6_fu_1029_p2;
    end else if ((((current_state == 3'd3) & (tx_r_rd_V_read_read_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd3) & (1'b1 == ap_CS_fsm_state1)) | ((tx_r_rd_V == 1'd1) & (current_state == 3'd3) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_nbreadreq_fu_307_p3 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_nbreadreq_fu_307_p3 == 1'd0) & (tmp_2_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state == 3'd4) & (tx_r_rd_V_read_read_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd5) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd7) & (1'b1 == ap_CS_fsm_state1)) | ((current_state_load_load_fu_798_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_sop_V_new_1_phi_fu_440_p26 = 1'd0;
    end else begin
        ap_phi_mux_sop_V_new_1_phi_fu_440_p26 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_733)) begin
        if ((tmp_2_fu_819_p2 == 1'd1)) begin
            ap_phi_mux_storemerge1_phi_fu_420_p4 = 14'd2;
        end else if ((tmp_2_fu_819_p2 == 1'd0)) begin
            ap_phi_mux_storemerge1_phi_fu_420_p4 = grp_fu_709_p2;
        end else begin
            ap_phi_mux_storemerge1_phi_fu_420_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge1_phi_fu_420_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_736)) begin
        if ((tmp_2_fu_819_p2 == 1'd1)) begin
            ap_phi_mux_storemerge2_phi_fu_430_p4 = 14'd6;
        end else if ((tmp_2_fu_819_p2 == 1'd0)) begin
            ap_phi_mux_storemerge2_phi_fu_430_p4 = grp_fu_709_p2;
        end else begin
            ap_phi_mux_storemerge2_phi_fu_430_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge2_phi_fu_430_p4 = 'bx;
    end
end

always @ (*) begin
    if (((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((word_byte_V_load_load_fu_1145_p1 == 4'd0)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_fu_1318_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd1)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_1_fu_1307_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd2)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_2_fu_1296_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd3)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_3_fu_1285_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd4)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_4_fu_1274_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd5)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_5_fu_1263_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd6)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_6_fu_1252_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd7)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_7_fu_1241_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd8)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_8_fu_1230_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd9)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_9_fu_1219_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd10)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_10_fu_1208_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd11)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_11_fu_1197_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd12)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_12_fu_1186_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd13)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_13_fu_1175_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd14)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_14_fu_1164_p4;
        end else if ((word_byte_V_load_load_fu_1145_p1 == 4'd15)) begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = temp_data_V_15_fu_1153_p4;
        end else begin
            ap_phi_mux_tmp_V_3_phi_fu_571_p34 = 'bx;
        end
    end else begin
        ap_phi_mux_tmp_V_3_phi_fu_571_p34 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge8_fu_1357_p2 == 1'd0)) begin
            ap_phi_mux_word_byte_V_flag_1_phi_fu_684_p4 = 1'd1;
        end else if ((brmerge8_fu_1357_p2 == 1'd1)) begin
            ap_phi_mux_word_byte_V_flag_1_phi_fu_684_p4 = ap_phi_mux_word_byte_V_flag_phi_fu_633_p4;
        end else begin
            ap_phi_mux_word_byte_V_flag_1_phi_fu_684_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_word_byte_V_flag_1_phi_fu_684_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge1016_demorgan_fu_1127_p2 == 1'd1)) begin
            ap_phi_mux_word_byte_V_flag_phi_fu_633_p4 = not_tmp_s_fu_1343_p2;
        end else if ((brmerge1016_demorgan_fu_1127_p2 == 1'd0)) begin
            ap_phi_mux_word_byte_V_flag_phi_fu_633_p4 = 1'd0;
        end else begin
            ap_phi_mux_word_byte_V_flag_phi_fu_633_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_word_byte_V_flag_phi_fu_633_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((brmerge8_fu_1357_p2 == 1'd0)) begin
            ap_phi_mux_word_byte_V_new_1_phi_fu_695_p4 = 4'd0;
        end else if ((brmerge8_fu_1357_p2 == 1'd1)) begin
            ap_phi_mux_word_byte_V_new_1_phi_fu_695_p4 = tmp_18_fu_1336_p2;
        end else begin
            ap_phi_mux_word_byte_V_new_1_phi_fu_695_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_word_byte_V_new_1_phi_fu_695_p4 = 'bx;
    end
end

always @ (*) begin
    if (((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_predicate_op110_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (ap_predicate_op95_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_buffer_V_V_read = 1'b1;
    end else begin
        data_buffer_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_buffer_V_V_write = 1'b1;
    end else begin
        data_buffer_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((brmerge8_fu_1357_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_in_V_V_TDATA_blk_n = data_in_V_V_TVALID;
    end else begin
        data_in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (brmerge8_fu_1357_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_in_V_V_TREADY = 1'b1;
    end else begin
        data_in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = (((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_109 = (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_193 = (~(((brmerge1016_demorgan_fu_1127_p2 == 1'd1) & (data_buffer_V_V_full_n == 1'b0)) | ((ap_predicate_op110_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((ap_predicate_op95_read_state1 == 1'b1) & (data_buffer_V_V_empty_n == 1'b0)) | ((data_in_V_V_TVALID == 1'b0) & (brmerge8_fu_1357_p2 == 1'd0))) & (current_state_load_load_fu_798_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_733 = ((tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_736 = ((tx_r_rd_V == 1'd1) & (current_state_load_load_fu_798_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_predicate_op110_read_state1 = ((tmp_2_fu_819_p2 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd3));
end

always @ (*) begin
    ap_predicate_op95_read_state1 = ((tmp_nbreadreq_fu_307_p3 == 1'd1) & (tx_r_rd_V == 1'd1) & (current_state == 3'd4) & (tmp_2_fu_819_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign brmerge1016_demorgan_fu_1127_p1 = data_buffer_V_V_full_n;

assign brmerge1016_demorgan_fu_1127_p2 = (data_word_valid & brmerge1016_demorgan_fu_1127_p1);

assign brmerge1_fu_1381_p2 = (p_not1_fu_1375_p2 | ap_phi_mux_buffer_removed_5_phi_fu_527_p26);

assign brmerge2_fu_1417_p2 = (buffer_removed_5_not_fu_1411_p2 | ap_phi_mux_buffer_added_new_phi_fu_612_p4);

assign brmerge8_fu_1357_p2 = (tmp_27_not_fu_1351_p2 | ap_phi_mux_data_word_valid_load_1_phi_fu_653_p4);

assign buffer_added_load_load_fu_811_p1 = buffer_added;

assign buffer_removed_5_not_fu_1411_p2 = (ap_phi_mux_buffer_removed_5_phi_fu_527_p26 ^ 1'd1);

assign current_state_load_load_fu_798_p1 = current_state;

assign demorgan_fu_1054_p0 = data_buffer_V_V_empty_n;

assign demorgan_fu_1054_p2 = (p_not_fu_1048_p2 & demorgan_fu_1054_p0);

assign dma_tx_status_tog_V = last_tx_status_valid;

assign grp_fu_709_p2 = ($signed(count_V) + $signed(14'd16383));

assign not_tmp_s_fu_1343_p2 = (tmp_17_fu_1329_p2 ^ 1'd1);

integer ap_tvar_int_0;

always @ (p_Result_s_fu_1060_p4) begin
    for (ap_tvar_int_0 = 14 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 13 | ap_tvar_int_0 < 4) begin
            p_Result_2_fu_1070_p5[ap_tvar_int_0] = ap_const_lv14_0[ap_tvar_int_0];
        end else if (13 - ap_tvar_int_0 >= 10) begin
            p_Result_2_fu_1070_p5[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_2_fu_1070_p5[ap_tvar_int_0] = p_Result_s_fu_1060_p4[13 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (count_V) begin
    for (ap_tvar_int_1 = 4 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 3 - 0) begin
            p_Result_6_fu_1019_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_6_fu_1019_p4[ap_tvar_int_1] = count_V[3 - ap_tvar_int_1];
        end
    end
end

assign p_Result_7_fu_877_p4 = {{length_V[15:8]}};

integer ap_tvar_int_2;

always @ (buffer_count_V) begin
    for (ap_tvar_int_2 = 10 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 13 - 4) begin
            p_Result_s_fu_1060_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            p_Result_s_fu_1060_p4[ap_tvar_int_2] = buffer_count_V[13 - ap_tvar_int_2];
        end
    end
end

assign p_cast_fu_1106_p1 = p_s_fu_1098_p3;

assign p_not1_fu_1375_p2 = (ap_phi_mux_buffer_added_new_phi_fu_612_p4 ^ 1'd1);

assign p_not_fu_1048_p2 = ((count_V == 14'd0) ? 1'b1 : 1'b0);

assign p_s_fu_1098_p3 = ((tmp_9_fu_1082_p2[0:0] === 1'b1) ? 15'd49 : tmp_5_fu_1092_p2);

assign packet_buffered_fu_761_p2 = ((buffer_count_V > 14'd1487) ? 1'b1 : 1'b0);

assign storemerge_in_in_fu_891_p3 = ((tmp_s_fu_871_p2[0:0] === 1'b1) ? p_Result_7_fu_877_p4 : tmp_23_fu_887_p1);

integer ap_tvar_int_3;

always @ (data_word_V) begin
    for (ap_tvar_int_3 = 8 - 1; ap_tvar_int_3 >= 0; ap_tvar_int_3 = ap_tvar_int_3 - 1) begin
        if (ap_tvar_int_3 > 87 - 80) begin
            temp_data_V_10_fu_1208_p4[ap_tvar_int_3] = 1'b0;
        end else begin
            temp_data_V_10_fu_1208_p4[ap_tvar_int_3] = data_word_V[87 - ap_tvar_int_3];
        end
    end
end

integer ap_tvar_int_4;

always @ (data_word_V) begin
    for (ap_tvar_int_4 = 8 - 1; ap_tvar_int_4 >= 0; ap_tvar_int_4 = ap_tvar_int_4 - 1) begin
        if (ap_tvar_int_4 > 95 - 88) begin
            temp_data_V_11_fu_1197_p4[ap_tvar_int_4] = 1'b0;
        end else begin
            temp_data_V_11_fu_1197_p4[ap_tvar_int_4] = data_word_V[95 - ap_tvar_int_4];
        end
    end
end

integer ap_tvar_int_5;

always @ (data_word_V) begin
    for (ap_tvar_int_5 = 8 - 1; ap_tvar_int_5 >= 0; ap_tvar_int_5 = ap_tvar_int_5 - 1) begin
        if (ap_tvar_int_5 > 103 - 96) begin
            temp_data_V_12_fu_1186_p4[ap_tvar_int_5] = 1'b0;
        end else begin
            temp_data_V_12_fu_1186_p4[ap_tvar_int_5] = data_word_V[103 - ap_tvar_int_5];
        end
    end
end

integer ap_tvar_int_6;

always @ (data_word_V) begin
    for (ap_tvar_int_6 = 8 - 1; ap_tvar_int_6 >= 0; ap_tvar_int_6 = ap_tvar_int_6 - 1) begin
        if (ap_tvar_int_6 > 111 - 104) begin
            temp_data_V_13_fu_1175_p4[ap_tvar_int_6] = 1'b0;
        end else begin
            temp_data_V_13_fu_1175_p4[ap_tvar_int_6] = data_word_V[111 - ap_tvar_int_6];
        end
    end
end

integer ap_tvar_int_7;

always @ (data_word_V) begin
    for (ap_tvar_int_7 = 8 - 1; ap_tvar_int_7 >= 0; ap_tvar_int_7 = ap_tvar_int_7 - 1) begin
        if (ap_tvar_int_7 > 119 - 112) begin
            temp_data_V_14_fu_1164_p4[ap_tvar_int_7] = 1'b0;
        end else begin
            temp_data_V_14_fu_1164_p4[ap_tvar_int_7] = data_word_V[119 - ap_tvar_int_7];
        end
    end
end

integer ap_tvar_int_8;

always @ (data_word_V) begin
    for (ap_tvar_int_8 = 8 - 1; ap_tvar_int_8 >= 0; ap_tvar_int_8 = ap_tvar_int_8 - 1) begin
        if (ap_tvar_int_8 > 127 - 120) begin
            temp_data_V_15_fu_1153_p4[ap_tvar_int_8] = 1'b0;
        end else begin
            temp_data_V_15_fu_1153_p4[ap_tvar_int_8] = data_word_V[127 - ap_tvar_int_8];
        end
    end
end

integer ap_tvar_int_9;

always @ (data_word_V) begin
    for (ap_tvar_int_9 = 8 - 1; ap_tvar_int_9 >= 0; ap_tvar_int_9 = ap_tvar_int_9 - 1) begin
        if (ap_tvar_int_9 > 15 - 8) begin
            temp_data_V_1_fu_1307_p4[ap_tvar_int_9] = 1'b0;
        end else begin
            temp_data_V_1_fu_1307_p4[ap_tvar_int_9] = data_word_V[15 - ap_tvar_int_9];
        end
    end
end

integer ap_tvar_int_10;

always @ (data_word_V) begin
    for (ap_tvar_int_10 = 8 - 1; ap_tvar_int_10 >= 0; ap_tvar_int_10 = ap_tvar_int_10 - 1) begin
        if (ap_tvar_int_10 > 23 - 16) begin
            temp_data_V_2_fu_1296_p4[ap_tvar_int_10] = 1'b0;
        end else begin
            temp_data_V_2_fu_1296_p4[ap_tvar_int_10] = data_word_V[23 - ap_tvar_int_10];
        end
    end
end

integer ap_tvar_int_11;

always @ (data_word_V) begin
    for (ap_tvar_int_11 = 8 - 1; ap_tvar_int_11 >= 0; ap_tvar_int_11 = ap_tvar_int_11 - 1) begin
        if (ap_tvar_int_11 > 31 - 24) begin
            temp_data_V_3_fu_1285_p4[ap_tvar_int_11] = 1'b0;
        end else begin
            temp_data_V_3_fu_1285_p4[ap_tvar_int_11] = data_word_V[31 - ap_tvar_int_11];
        end
    end
end

integer ap_tvar_int_12;

always @ (data_word_V) begin
    for (ap_tvar_int_12 = 8 - 1; ap_tvar_int_12 >= 0; ap_tvar_int_12 = ap_tvar_int_12 - 1) begin
        if (ap_tvar_int_12 > 39 - 32) begin
            temp_data_V_4_fu_1274_p4[ap_tvar_int_12] = 1'b0;
        end else begin
            temp_data_V_4_fu_1274_p4[ap_tvar_int_12] = data_word_V[39 - ap_tvar_int_12];
        end
    end
end

integer ap_tvar_int_13;

always @ (data_word_V) begin
    for (ap_tvar_int_13 = 8 - 1; ap_tvar_int_13 >= 0; ap_tvar_int_13 = ap_tvar_int_13 - 1) begin
        if (ap_tvar_int_13 > 47 - 40) begin
            temp_data_V_5_fu_1263_p4[ap_tvar_int_13] = 1'b0;
        end else begin
            temp_data_V_5_fu_1263_p4[ap_tvar_int_13] = data_word_V[47 - ap_tvar_int_13];
        end
    end
end

integer ap_tvar_int_14;

always @ (data_word_V) begin
    for (ap_tvar_int_14 = 8 - 1; ap_tvar_int_14 >= 0; ap_tvar_int_14 = ap_tvar_int_14 - 1) begin
        if (ap_tvar_int_14 > 55 - 48) begin
            temp_data_V_6_fu_1252_p4[ap_tvar_int_14] = 1'b0;
        end else begin
            temp_data_V_6_fu_1252_p4[ap_tvar_int_14] = data_word_V[55 - ap_tvar_int_14];
        end
    end
end

integer ap_tvar_int_15;

always @ (data_word_V) begin
    for (ap_tvar_int_15 = 8 - 1; ap_tvar_int_15 >= 0; ap_tvar_int_15 = ap_tvar_int_15 - 1) begin
        if (ap_tvar_int_15 > 63 - 56) begin
            temp_data_V_7_fu_1241_p4[ap_tvar_int_15] = 1'b0;
        end else begin
            temp_data_V_7_fu_1241_p4[ap_tvar_int_15] = data_word_V[63 - ap_tvar_int_15];
        end
    end
end

integer ap_tvar_int_16;

always @ (data_word_V) begin
    for (ap_tvar_int_16 = 8 - 1; ap_tvar_int_16 >= 0; ap_tvar_int_16 = ap_tvar_int_16 - 1) begin
        if (ap_tvar_int_16 > 71 - 64) begin
            temp_data_V_8_fu_1230_p4[ap_tvar_int_16] = 1'b0;
        end else begin
            temp_data_V_8_fu_1230_p4[ap_tvar_int_16] = data_word_V[71 - ap_tvar_int_16];
        end
    end
end

integer ap_tvar_int_17;

always @ (data_word_V) begin
    for (ap_tvar_int_17 = 8 - 1; ap_tvar_int_17 >= 0; ap_tvar_int_17 = ap_tvar_int_17 - 1) begin
        if (ap_tvar_int_17 > 79 - 72) begin
            temp_data_V_9_fu_1219_p4[ap_tvar_int_17] = 1'b0;
        end else begin
            temp_data_V_9_fu_1219_p4[ap_tvar_int_17] = data_word_V[79 - ap_tvar_int_17];
        end
    end
end

integer ap_tvar_int_18;

always @ (data_word_V) begin
    for (ap_tvar_int_18 = 8 - 1; ap_tvar_int_18 >= 0; ap_tvar_int_18 = ap_tvar_int_18 - 1) begin
        if (ap_tvar_int_18 > 7 - 0) begin
            temp_data_V_fu_1318_p4[ap_tvar_int_18] = 1'b0;
        end else begin
            temp_data_V_fu_1318_p4[ap_tvar_int_18] = data_word_V[7 - ap_tvar_int_18];
        end
    end
end

assign tmp_11_fu_985_p1 = count_V[2:0];

assign tmp_14_fu_909_p2 = ($signed(14'd16383) + $signed(tmp_24_fu_905_p1));

assign tmp_15_cast_fu_1088_p1 = p_Result_2_fu_1070_p5;

assign tmp_17_fu_1329_p2 = ((word_byte_V == 4'd15) ? 1'b1 : 1'b0);

assign tmp_18_fu_1336_p2 = (word_byte_V + 4'd1);

assign tmp_20_fu_1399_p2 = (buffer_count_V + 14'd1);

assign tmp_21_fu_1423_p2 = ($signed(buffer_count_V) + $signed(14'd16383));

assign tmp_22_fu_933_p1 = count_V[2:0];

assign tmp_23_fu_887_p1 = length_V[7:0];

assign tmp_24_fu_905_p1 = length_V[13:0];

assign tmp_27_not_fu_1351_p0 = data_in_V_V_TVALID;

assign tmp_27_not_fu_1351_p2 = (tmp_27_not_fu_1351_p0 ^ 1'd1);

assign tmp_2_fu_819_p2 = ((count_V == 14'd1) ? 1'b1 : 1'b0);

assign tmp_3_fu_995_p7 = ($signed(3'd6) - $signed(tmp_11_fu_985_p1));

assign tmp_4_fu_943_p7 = ($signed(3'd6) - $signed(tmp_22_fu_933_p1));

assign tmp_5_fu_1092_p2 = (tmp_15_cast_fu_1088_p1 + 15'd1);

assign tmp_6_fu_1029_p2 = ((p_Result_6_fu_1019_p4 == 4'd6) ? 1'b1 : 1'b0);

assign tmp_8_fu_841_p2 = (ID_num_V + 8'd1);

assign tmp_9_fu_1082_p2 = ((p_Result_2_fu_1070_p5 < 14'd48) ? 1'b1 : 1'b0);

assign tmp_nbreadreq_fu_307_p3 = data_buffer_V_V_empty_n;

assign tmp_s_fu_871_p2 = ((count_V == 14'd2) ? 1'b1 : 1'b0);

assign tx_r_control_V = 1'd0;

assign tx_r_data_V = tx_data_V;

assign tx_r_data_rdy_V = data_ready_V;

assign tx_r_eop_V = eop_V;

assign tx_r_err_V = 1'd0;

assign tx_r_flushed_V = 1'd0;

assign tx_r_rd_V_read_read_fu_288_p2 = tx_r_rd_V;

assign tx_r_sop_V = sop_V;

assign tx_r_underflow_V = 1'd0;

assign tx_r_valid_V = tx_valid_V;

assign word_byte_V_load_load_fu_1145_p1 = word_byte_V;

always @ (posedge ap_clk) begin
    length_V[15] <= 1'b0;
end

endmodule //eth_fifo_interface
